# Generated by Django 5.2.8 on 2025-12-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_bb_king'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='king',
        ),
        migrations.AddField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('Купля-продажа', [('b', 'Куплю'), ('s', 'Продам')]), ('Обмен', [('c', 'Обменяю')])], default='s', max_length=1),
        ),
    ]
