# Generated by Django 5.2.8 on 2025-12-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_remove_bb_king_bb_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('Купля-продажа', [('b', 'Куплю'), ('s', 'Продам')]), ('Обмен', [('c', 'Обменяю')])], default='s', max_length=1, verbose_name='Тип объявления'),
        ),
    ]
